### ISSUE TITLE
OperationalError even though the table exists when exporting to PDF / HTML

### ISSUE THREAD

**Issue by lbeltrame** [robinandeer/chanjo-report#10]
Divided into multiline for simplicity:
```python
sqlalchemy.exc.OperationalError: (OperationalError) no such table:
sample 'SELECT sample.id AS sample_id, sample.group_id AS sample_group_id, sample.cutoff AS 
sample_cutoff, sample.extension AS sample_extension, sample.coverage_source AS sample_coverage_source, sample.element_source AS sample_element_source, sample.created_at AS sample_created_at, sample.updated_at AS sample_updated_at
FROM sample
WHERE sample.id = ? ORDER BY sample.id' ('mysample',)
````

But:

```
sqlite> .tables
block            interval         interval_data    superblock     
block_data       interval__block  sample           superblock_data
sqlite> 
```

**Comment by lbeltrame** [comment]
The reason is that --db and even the output has no effect, and instead an empty `chanjo.sqlite` file is created. That's because if `uri` is None (somehow `--db ` is ignored) the value supplied by the user is *not* set.

**Comment by robinandeer** [comment]
Hmmm... how are you calling ``chanjo report``. I can think of one reason for this which is related to how ``Click`` (the CLI framework used) works.

``--db`` belongs to the root level ``chanjo`` command and must therefore be supplied before any subcommand. I would've guessed it would've raised an error though.

Right:

```bash
$ chanjo --db coverage.sqlite3 report ...
```

Doesn't work:

```bash
$ chanjo report --db coverage.sqlite3 ...
```
