### ISSUE TITLE
"Please enter path to database" writes to stdout

### ISSUE THREAD

**Issue by lbeltrame** [robinandeer/chanjo-report#11]
This makes writing PDFs impossible (bogus data written along with the real data).

**Comment by robinandeer** [comment]
I agree that such a message should at least write to ``STDERR``. It seems like an error that should halt execution completely though... What is your full command you are running? And what if any information do you have in your ``chanjo.toml`` config file?

**Comment by robinandeer** [comment]
Since you can't generate data without locating a database I will close this issue
